apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Hello_World_Quarkus_Application"
  annotations:
    argocd/app-name: my-quarkus-app2-dev
    backstage.io/kubernetes-id: my-quarkus-app2
    backstage.io/kubernetes-namespace: my-quarkus-app2-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: assemble-dev-org/backstage-sample-quarkus-app2
    quay.io/repository-slug: "/my-quarkus-app2"
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-hx87f.hx87f.sandbox3154.opentlc.com/#https://github.com/assemble-dev-org/backstage-sample-quarkus-app2?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-hx87f.hx87f.sandbox3154.opentlc.com/#https://github.com/assemble-dev-org/backstage-sample-quarkus-app2?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/jayfray62"
  system: janus-idp
  providesApis:
    - "my-quarkus-app2"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "Hello_World_Quarkus_Application"
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/jayfray62"
  definition:
    $text: ./openapi.yaml
